set_property PACKAGE_PIN A18 [get_ports K1]
set_property PACKAGE_PIN B18 [get_ports K2]
set_property PACKAGE_PIN A17 [get_ports L1]
set_property IOSTANDARD LVCMOS33 [get_ports K1]
set_property IOSTANDARD LVCMOS33 [get_ports K2]
set_property IOSTANDARD LVCMOS33 [get_ports L1]
set_property IOSTANDARD LVCMOS33 [get_ports K3]
set_property IOSTANDARD LVCMOS33 [get_ports K4]
set_property IOSTANDARD LVCMOS33 [get_ports L2]
set_property IOSTANDARD LVCMOS33 [get_ports L3]
set_property IOSTANDARD LVCMOS33 [get_ports L4]
set_property PACKAGE_PIN C16 [get_ports L2]
set_property PACKAGE_PIN C17 [get_ports L3]
set_property PACKAGE_PIN B16 [get_ports L4]

set_property PACKAGE_PIN G17 [get_ports K3]
set_property PACKAGE_PIN G19 [get_ports K4]

