#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Oct 01 19:06:50 CEST 2023
# SW Build 3900603 on Fri Jun 16 19:30:25 MDT 2023
#
# IP Build 3900379 on Sat Jun 17 05:28:05 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Top_behav -key {Behavioral:sim_1:Functional:Top} -tclbatch Top.tcl -view /home/mikkel/repoes/ESD3/ESD3-Opgaver/DigitalHardwareDesign/DHD KG7/EX 4/Top_behav.wcfg -log simulate.log"
xsim Top_behav -key {Behavioral:sim_1:Functional:Top} -tclbatch Top.tcl -view /home/mikkel/repoes/ESD3/ESD3-Opgaver/DigitalHardwareDesign/DHD KG7/EX 4/Top_behav.wcfg -log simulate.log

